### ISSUE TITLE
Initial Update for BSidesRDU 2019

### ISSUE THREAD

**Issue by unregistered436** [BSidesRDU/website#12]
Please update the site to reflect the new 2019 Information by May 4th.
This year's date is October 18, 2019
Remove last year's schedule, and mention that the CFP is currently open. Link to CFP is https://sessionize.com/bsidesrdu-2018/  (opens on May 4)
Remove the Hands On Village from the Side Events
Remove the registration section under buy tickets and replace with a message that tickets will be on sale "soon".
Add a message above the sponsor logos that "Last year's sponsors included ...". TBH, I'd remove the "Click here to become a sponsor" link as well because we're still working through the rates and benefits of sponsorship.

**Comment by santosomar** [comment]
Hi! Glad to help on this! FYI: when I go to the CFP site (which the URL still says 2018) I get the following warning: 

> "This event is in trial mode and can be used just for testing. Number of submissions is limited"

Would you like me to still link it?

**Comment by unregistered436** [comment]
Can you make that update on May 4th? :)

**Comment by santosomar** [comment]
absolutely... ;-) I am at least cleaning up the old stuff and just updating the date, etc...

**Comment by santosomar** [comment]
It said, "by May 4th" (be the 4th be with you) ;-) so I was at least cleaning stuff early.

**Comment by santosomar** [comment]
These are the updates from me:


> This year's date is October 18, 2019

Done.

> Remove last year's schedule, and mention that the CFP is currently open. Link to CFP is https://sessionize.com/bsidesrdu-2018/ (opens on May 4)

I added just a text saying "coming soon!" Will edit on May 4th.

> Remove the Hands On Village from the Side Events
Done.

> Remove the registration section under buy tickets and replace with a message that tickets will be on sale "soon".
Done

> Add a message above the sponsor logos that "Last year's sponsors included ...". TBH, I'd remove the "Click here to become a sponsor" link as well because we're still working through the rates and benefits of sponsorship.

Done

**Comment by unregistered436** [comment]
Thanks! That was fast ;)

Hands on Village still appears for me?

**Comment by santosomar** [comment]
The change should be there now...

**Comment by santosomar** [comment]
Updated website with CFP information. Sorry for the delay.
